### PR TITLE
Add type exports to package.json

### PR DESCRIPTION
**Pull request by mrdrogdrog**
Same as https://github.com/yjs/y-protocols/pull/21

### CODE REVIEW

**Comment by mrdrogdrog** [comment]
bump

**Comment by dmonad** [comment]
The types are located in the root folder next to the original files. Hence, it shouldn't be necessary to explicitly link to the files..

Before you make another PR, can you please explain how your typescript version doesn't find the type definitions?

**Comment by mrdrogdrog** [comment]
So I ask you to merge this pull request. Otherwise I can't use this lib (and y-protocols) with esmodule libs and would need to replace it. :/

**Comment by mrdrogdrog** [comment]
Did you have a chance to take a look at this again?

**Comment by dmonad** [comment]
@mrdrogdrog 

As I said before, the type declarations are located next to the original files. So "./dist/array.d.ts"` doesn't exist. This PR is untested and will break everyone else.

So before you make another PR. Please explain why the current approach doesn't work. What is your setup? Why does it work for everyone else but you?

Second, you need to change your PR to point to the actual type declarations: `./array.d.ts` not `./dist/array.d.ts`

Third, you need to test the PR and ensure it actually works. Please also show me how I can verify that it works in the future.

**Comment by mrdrogdrog** [comment]
> As I said before, the type declarations are located next to the original files. So "./dist/array.d.ts"` doesn't exist.

Nope. they exist.

image

But okay. Since you prefer the top level type files I changed the code.

> This PR is untested and will break everyone else.

No. I've tested it locally and it works. It doesn't break anything since the export object is only used if typescript is using the ESM resolver.

> So before you make another PR. Please explain why the current approach doesn't work. What is your setup? Why does it work for everyone else but you?

Like I explained before [here](https://github.com/dmonad/lib0/pull/40#issuecomment-1300721591) a full module setup relies only on the export object and doesn't assume the location of type files. 

I guess most of the people use the default configuration of typescript for module resolution. This is the commonjs module resolver which still assumes the location of type files.
My project(s) (at least the libraries) use rollup to create MJS and CJS exports. I create these libs in typescript and have configured typescript to produce ESM files. Then I use rollup (microbundle to be precise) to generate cjs code. I do this by telling typescript to use the newer module resolver which relies on the exports object. Therefore the dependencies have to be either commonjs packages or export the type declaration files.

image

I recorded this quick video to demonstrate the effect of the modified package.json . I used my lib's test cases because the tests are also written in typescript and therefore also use the ESM resolver.

https://user-images.githubusercontent.com/6124140/205284159-6e238004-abd4-45ef-abe5-8f0a42714f18.mp4

**Comment by mrdrogdrog** [comment]
btw: yjs already exports the types https://github.com/yjs/yjs/blob/main/package.json#L29 . That's why this lib doesn't produce such errors.

**Pull request closed without merging**
