### PR TITLE
indexeddb: ignore blocked event

### PR DESCRIPTION
**Pull request by raineorshine**
#55

### CODE REVIEW

**Comment by raineorshine** [comment]
I have commented out the `onblocked` handlers and added a basic test.

Emitting the `blocked` event is another question. The request object is wrapped in a promise, so there is no way to bubble up the event. The ideas I have so far are:

1. Change the `indexeddb` module from promise-based to event-based, returning an emitter that emits `success`, `error`, and `blocked` events. Major change to the API.
2. Return a custom promise which supports `.on('blocked`, ...)`. Non-breaking, but unconventional.
3. Fire a [custom event](https://developer.mozilla.org/en-US/docs/Web/Events/Creating_and_triggering_events#adding_custom_data_%E2%80%93_customevent) on the window object:
   ```js
   const e = new CustomEvent('lib0.indexeddb.blocked', { detail: { request } })
   dispatchEvent(e)
   ```

Open to your thoughts.

**Comment by raineorshine** [comment]
@dmonad

**Comment by dmonad** [comment]
The `blocked` event is, as the spec describes it, a "progress report". So there can potentially be multiple `blocked` events. Hence I wouldn't go with 1-3.

I agree with 4. If the database can't be opened, we could reject the promise with a custom error. This is only necessary when opening the database - other requests can't be blocked (if I understand the spec correctly).

If you want to add a PR for this: I suggest making the timeout configurable but with a sensible default (e.g. 15s).

**Comment by dmonad** [comment]
Thanks for the PR!

I will release it in a bit ;)

**Pull request merged**
