### PR TITLE
Cleanup and Observable once fix

### PR DESCRIPTION
**Pull request by danieldahan**
Hi, 

You have an issue with your Observable `once` API. It doesn't work. I made a fix for it, which now works. As well, no need to include your .vscode directory, and a couple other files that don't need to be committed.

### CODE REVIEW

**Comment by dmonad** [comment]
Hi @danieldahan , 

I appreciate that you took the initiative to fix the issue! Yeah, this is a bug, thanks for fixing it.

But in my projects I do commit package-lock.json (as is recommended) and I do commit .vscode files (just because I like it).

Would you like to publish another PR? Otherwise, I'm going to fix it in the next release.

**Comment by dmonad** [comment]
Looking at your github profile I guess you don't need the fame / experience of committing to this project ^^ I'm simply gonna publish a new release with the fix. Will be ready in a bit.

**Comment by dmonad** [comment]
Fixed in 0.2.34

**Comment by danieldahan** [comment]
Thank you!! I was going to suggest to just fix it. I love your YJS project. My team and I have done something special with it that I think you would appreciate. I'll share when ready. All the best!

**Comment by dmonad** [comment]
@danieldahan Looking at CosmicMind I can't wait :) 

Hook me up ASAP and if you want you could "show-off" your project in https://discuss.yjs.dev/.

**Comment by danieldahan** [comment]
@dmonad Thank you! I plan to sponsor you once it is up and running :) And I'd love to share what we have done. Thanks again!

**Pull request closed without merging**
